### ISSUE TITLE
I thought its cool to turn the github into blog site but

### ISSUE THREAD

**Issue by AntDX316** [daveshap/Narratives_Emergence_Convergence#1]
I thought its cool to turn the github into a blog site but the inability for people to comment and the way the photos are inside the hierarchy isn't good.

It's understandable to not use a custom forum but I think it would be better if you created a subreddit?

I think people turning Patreon into a blog site is bad as well, although understandable. I think creating a subreddit is the best to do as it's easy to see people's ideas. It's setup with the ability for people to have push notifications and such as well as messaging each other to further iterate on ideas that weren't really thought of before.

**Comment by daveshap** [comment]
This isn't a blog. It's a collaborate book.
